---
title: "NBA 2014-2015球季 各隊分析"
output: github_document
---

```{r echo=T}
  #install.packages("SportsAnalytics")
  library(SportsAnalytics)
  NBA1415<-fetch_NBAPlayerStatistics("14-15")
```

##各隊最辛苦的球員

計算依據出戰分鐘數最多的球員


```{r echo=T}
MaxMinutesPlayed<-aggregate(TotalMinutesPlayed~Team,NBA1415,max)
NBA1415MaxMinutesPlayed<-merge(NBA1415,MaxMinutesPlayed)
output<-NBA1415MaxMinutesPlayed[order(NBA1415MaxMinutesPlayed$TotalMinutesPlayed,decreasing = T),c("Team","Name","TotalMinutesPlayed")]
library(knitr)
kable(output, digits = 2)
```

##各隊得分王

計算依據為總得分最多的球員

```{r echo=T}
MaxPoint<-aggregate(TotalPoints~Team,NBA1415,max)
NBA1415MaxPoint<-merge(NBA1415,MaxPoint)
output<-NBA1415MaxPoint[order(NBA1415MaxPoint$TotalPoints,decreasing = T),c("Team","Name","TotalPoints")]
library(knitr)
kable(output, digits = 2)
```

##各隊最有效率的球員

總得分/出戰分鐘數 最高的球員

```{r echo=T}
MostEfficient<-aggregate(TotalPoints/TotalMinutesPlayed ~Team+Name+TotalPoints+TotalMinutesPlayed,NBA1415,max)
names(MostEfficient)<- c("Team","Name","TotalPoints","TotalMinutesPlayed","Efficient")
TheMostEfficient<-aggregate(Efficient~Team,MostEfficient,max)
NBA1415MostEfficient<-merge(MostEfficient,TheMostEfficient)
output<-NBA1415MostEfficient[order(NBA1415MostEfficient$Efficient,decreasing = T),c("Team","Name","Efficient")]
library(knitr)
kable(output, digits = 2)
```

##各隊三分球出手最準的球員

ThreeMades/ThreesAttempted 最高的球員

```{r echo=T}
ThreesMostAccurate<-aggregate(ThreesMade/ThreesAttempted~Team+Name+ThreesMade+ThreesAttempted,NBA1415,max)
names(ThreesMostAccurate)<- c("Team","Name","ThreesMade","ThreesAttempted","Accurate")
TheThreesMostAccurate<-aggregate(Accurate~Team,ThreesMostAccurate,max)
NBA1415ThreesMostAccurate<-merge(ThreesMostAccurate,TheThreesMostAccurate)
output<-NBA1415ThreesMostAccurate[order(NBA1415ThreesMostAccurate$Accurate,decreasing = T),c("Team","Name","Accurate")]
library(knitr)
kable(output, digits = 2)
```

