---
title: "糖尿病預測模型"
output: github_document
---
## 資料前處理

### 資料讀取
此資料來源為UCI Machine Learning Repository。

```{r message=F,warning=F}
if (!require('mlbench')){
    install.packages("mlbench")
}
 
 library(mlbench)
 data(PimaIndiansDiabetes)
 head(PimaIndiansDiabetes)
 
 
PimaIndiansDiabetesC<-PimaIndiansDiabetes[complete.cases(PimaIndiansDiabetes),]
c(nrow(PimaIndiansDiabetes),nrow(PimaIndiansDiabetesC))
```

### 將資料隨機分為訓練組與測試組

隨機將2/3的資料分到訓練組（Test==F），剩下1/3為測試組（Test==T)

```{r}
 PimaIndiansDiabetes$Test<-F
 PimaIndiansDiabetes[sample(1:nrow(PimaIndiansDiabetes),nrow(PimaIndiansDiabetes)/3),]$Test<-T
 c(sum(PimaIndiansDiabetes$Test==F),sum(PimaIndiansDiabetes$Test==T))
```

可得訓練組案例數為`r sum(PimaIndiansDiabetes$Test==F)`
測試組案例數為`r sum(PimaIndiansDiabetes$Test==T)`


## 預測模型建立

### 模型建立

感覺用回歸作起來比較好看
```{r warning=F,message=F}
fit<-glm(diabetes~., PimaIndiansDiabetes[PimaIndiansDiabetes$Test==F,],family="binomial")
library(MASS)
finalFit<-stepAIC(fit,direction = "both",trace = F)
summary(finalFit)$coefficients
```

由上述參數可知，由懷孕、葡萄糖、遺傳等等，以邏輯迴歸建立模型預測是否有糖尿病。


## 預測模型驗證
```{r warning=F,message=F,fig.height=4.5}
##PimaIndiansDiabetesPred<-predict(finalFit,newdata = PimaIndiansDiabetes[PimaIndiansDiabetes$Test==T,])
##PimaIndiansDiabetesAns<-ifelse(PimaIndiansDiabetesPred<0.5,"P","N") #<0.5: Level 1
##PimaIndiansDiabetesAns<-factor(PimaIndiansDiabetesAns,levels = c("P","N"))
##install.packages("caret")
##library(caret)
##sensitivity(PimaIndiansDiabetesAns,PimaIndiansDiabetes[PimaIndiansDiabetes$Test==T,]$diabetes)
##specificity(PimaIndiansDiabetesAns,PimaIndiansDiabetes[PimaIndiansDiabetes$Test==T,]$diabetes)
##posPredValue(PimaIndiansDiabetesAns,PimaIndiansDiabetes[PimaIndiansDiabetes$Test==T,]$diabetes)
##negPredValue(PimaIndiansDiabetesAns,PimaIndiansDiabetes[PimaIndiansDiabetes$Test==T,]$diabetes)
```
